### ISSUE TITLE
qwc-config-db and qwc-services-core docker tag or branch error

### ISSUE THREAD

**Issue by ngulesanlar** [qwc-services/qwc-docker#17]
Hi;
I'm new here. I'm trying to setup QWC from docker. While docker-composer Building process it throws some errors below:

_Collecting qwc-config-db from git+https://github.com/qwc-services/qwc-config-db.git@ee33dc8c0a0b405949e062036ee29b01bc4687b5#egg=qwc-config-db (from -r /srv/qwc-registration-gui/requirements.txt (line 9))
  Cloning https://github.com/qwc-services/qwc-config-db.git (to ee33dc8c0a0b405949e062036ee29b01bc4687b5) to /tmp/pip-build-f61n7wcm/qwc-config-db
  Could not find a tag or branch 'ee33dc8c0a0b405949e062036ee29b01bc4687b5', assuming commit.
Collecting qwc-services-core from git+https://github.com/qwc-services/qwc-services-core.git@d53015462234c787465252f952b4cb0d6dcb1641#egg=qwc-services-core (from -r /srv/qwc-registration-gui/requirements.txt (line 10))
  Cloning https://github.com/qwc-services/qwc-services-core.git (to d53015462234c787465252f952b4cb0d6dcb1641) to /tmp/pip-build-f61n7wcm/qwc-services-core
  Could not find a tag or branch 'd53015462234c787465252f952b4cb0d6dcb1641', assuming commit._

And then I  run docker-compose up -d process and everything looks good but I can see only map viewer (but no sample data) in my browser. /qwc_admin page throw "internal server error"
When I look up the docker-compose logs I see some errors below:

_qwc-auth-service_1 :      raise Exception("Install 'email_validator' for email validation support.")
qwc-config-service_1 :   *** Python threads support is disabled. You can enable it with --enable-threads ***
qwc-auth-service_1 :  --- no python application found, check your startup logs for errors ---_

etc.

Am I doing something wrong?  Help me please. I really have been struggling with this for a week.
Thanks in advance.

**Comment by HusseinKabbout** [comment]
@ngulesanlar Thanks for creating this issue!

The problem appears to be a missing module. I created a PR (https://github.com/qwc-services/qwc-db-auth/pull/2 
@pka) that adds the module to the requirements.

**Comment by ngulesanlar** [comment]
@HusseinKabbout ;
These links are placed in requirements.txt of some services.

git+https://github.com/qwc-services/qwc-config-db.git@ee33dc8c0a0b405949e062036ee29b01bc4687b5#egg=qwc-config-db
git+https://github.com/qwc-services/qwc-services-core.git@d53015462234c787465252f952b4cb0d6dcb1641#egg=qwc-services-core

Are these links broken?

**Comment by HusseinKabbout** [comment]
@ngulesanlar It looks like with those links, pip tries to clone a `tag` or a `branch` that is called `ee33dc8c0a0b405949e062036ee29b01bc4687b5`. What pip should actually do is, look for a commit with the specified SHA and install it . This shouldn't be a problem, because pip just looks for the latest commit and install it if it finds nothing.

In the near future the configDB service won't be used anymore and the `qwc-service-core` will be install from the official pypi repository. So both those problems should be fixed with that.

**Comment by ngulesanlar** [comment]
Okay. Thank you very much.
