### ISSUE TITLE
Wrong path of qwc-qgis-server demo config

### ISSUE THREAD

**Issue by grst** [qwc-services/qwc-docker#19]
I followed the instructions in the README and ran `docker-compose up`. When opening `http://localhost:8088` the map panel stays blank and the server log shows: 

```console
qwc-qgis-server_1              | [96][15:35:12] Error, configuration file '/data/ows/qwc_demo.qgs' does not exist
```

Moving the `qwc_demo.qgs` to the right location as follows solves the problem: 

```bash
mkdir volumes/qgs-resources/ows 
mv volumes/qgs-resources/qwc_demo.qgs volumes/qgs-resources/ows
```

**Comment by HusseinKabbout** [comment]
@grst I have freshly cloned the `qwc-docker` repository and didn't get the error message. To me this looks more like a configuration mistake in your `themesConfig.json` than a problem with the location of the project.

**Comment by grst** [comment]
Hmm... as far as I remember, I just used the example config file. 
There the path is `/ows/qwc_demo`

https://github.com/qwc-services/qwc-docker/blob/fd713f7dbe932950117945ad2df7c018201f76ea/volumes/qwc2/themesConfig-example.json#L9

which doesn't align with the location
of the demo `volumes/qgs-resources/qwc_demo.qgs`.

I might be mising something... feel free to close in that case.

**Comment by HusseinKabbout** [comment]
@grst The `url` configuration here refers to the `QGIS Server` url and not a path in the volumes directory.

**Comment by grst** [comment]
I see! Let's close this for now... should I ever encounter it again, I'll reopen with a full reproducible example.
