### ISSUE TITLE
Failing to start on windows

### ISSUE THREAD

**Issue by zoidable** [qwc-services/qwc-docker#2]
Hi there,

I'm trying to test the QWC "Suite" on a windows machine, but I can't seem to get it working end up getting the following error from docker-compose build:

> /tmp/docker-entrypoint.sh: /docker-entrypoint-initdb.d/0_setup-db.sh: /bin/bash^M: bad interpreter: No such file or directory
ERROR: Service 'qwc-postgis' failed to build: The command '/bin/sh -c gosu postgres bash /tmp/docker-entrypoint.sh postgres' returned a non-zero code: 126

I tried to resolve this by copying an empty docker-entrypoint.sh to /usr/local/bin/ at line 24 in the postgis Dockerfile, which kinda works, but then I end up with "unhealthy" containers for qwc-config-service and qwc-admin-gui.

Maybe this is also related to not knowing what the `cat >>~/.pg_service.conf <<EOS` command does (I entered the service configurations to each pg_service.conf in the subfolders). Could you help me out? I'd really like to see and test what the state of QWC and related services is...

Regards
Tobias

**Comment by All4Gis** [comment]
I had the same error,for fix on windows , install **cygwin** and run this command in all .sh files

Example for setup-db file : `sed -i -e 's/\r$//' setup-db.sh`

build the container

`docker-compose build`

and voilà run on windows

then, maybe you have some error but little by little it will work for you
