### ISSUE TITLE
qwc-solr Permission error

### ISSUE THREAD

**Issue by ngulesanlar** [qwc-services/qwc-docker#22]
Hi;
I noticed this error when I look at the docker-compose logs;

```
qwc-solr_1                     | Copying solr.xml
qwc-solr_1                     | cp: cannot create regular file '/var/solr/data/solr.xml': Permission denied
qwc-docker_qwc-solr_1 exited with code 1
```

I check my ubuntu permissions but there is no something wrong. I also use root user but there is the same error.

**Comment by HusseinKabbout** [comment]
@ngulesanlar This message basically means that the `qwc-solr` service doesn't have enough permissions to generate some data files in the mounted volumen `volume/solr/data`. What are the permissions on the `volume/solr/data` directory?

**Comment by HusseinKabbout** [comment]
Closing this issue, because the problem seems to be a permission issue and not directly a `qwc-docker` issue.

The solution to this issue is to give read/write permissions to the `volume/solr/data` directory.
