### ISSUE TITLE
README.md has wrong location for QWC2 translation files

### ISSUE THREAD

**Issue by beerockxs** [qwc-services/qwc-docker#3]
The readme file says to copy the QWC2 translation files like this:

cp -r translations/data.* $DSTDIR/qwc2

They need to be in $DSTDIR/qwc2/translations, otherwise the demo app won't work

**Comment by pka** [comment]
@HusseinKabbout: Could you check with @mwa?

**Comment by HusseinKabbout** [comment]
I checked with @mwa and he said that the correct path has to be `$DSTDIR/qwc2/translations`. So I made the following pull request (#10 ) with the fix.

**Comment by pka** [comment]
Thanks @beerockxs!
