### ISSUE TITLE
adding a new qgis project using costom postgis connection

### ISSUE THREAD

**Issue by ngulesanlar** [qwc-services/qwc-docker#31]
I'm trying to add a new qgis project but I'm failing.
we define volumes for pg_service file in other containers but qwc-qgis-server container.
qwc-qgis-server image contains a different pg_service file I think. 
How can we define a new postgis connection for qwc-qgis-server.
Thanks in advance.

**Comment by ngulesanlar** [comment]
I've defined a volume for qwc-qgis-server service in docker-compose.yml
`- ./pg_service.conf:/etc/postgresql-common/pg_service.conf`
I added my connection into ./pg_service.conf file
I prepared my qgs project using that connection
I copied this qgis project file into `/volumes/qgs-resources/` and `/volumes/config-in/default/qgis_projects/`
(I'm not sure which one is right so I copied the qgs file into both directories)
I defined resources and permissions for the map and data (via qwc_admin interface)
I can use the ogc service for qwc_demo but I can't for my qgs project.
Am I doing something wrong or need another definition?

**Comment by manisandro** [comment]
The current docker-compose-example will mount pg_service.conf to the correct location [1].

Besides that, please see [2].

[1] https://github.com/qwc-services/qwc-docker/blob/349d17779a93b8935482bbcb050170e1021ad781/docker-compose-example.yml#L18
[2] https://github.com/qwc-services/qwc-docker#adding-qgis-projects
