### ISSUE TITLE
error message when docker-compose up qwc-fulltext-search-service

### ISSUE THREAD

**Issue by kahermann** [qwc-services/qwc-docker#32]
Docker usage
To run this docker image you will need a running Solr search service.

solr dashboard is on http://localhost:8983/solr/#/

docker-compose up qwc-fulltext-search-service sends the error message

ERROR: for qwc-solr  Cannot start service qwc-solr: driver failed programming external connectivity on endpoint qwc-docker_qwc-solr_1 (fb79d10cff31cf547f856da93c0908604b326eb6641183bc0a5db051b0edac40): Error starting userland proxy: listen tcp 127.0.0.1:8983: bind: address already in use

**Comment by manisandro** [comment]
You likely have a service already bound to that port. Check with lsof or netstat.
