### ISSUE TITLE
questions: structure of maps and resources

### ISSUE THREAD

**Issue by AndreasAtakan** [qwc-services/qwc-docker#33]
Hi everyone,

I have compiled some questions regarding the structure of the maps and resources in the admin gui and the qwc-services as a whole;

- What is the purpose of the 'resources' in the admin gui?
  - Do they in any way control the data available in the qwc_demo database?
  - In that case, how do I view those resources in the map-viewer?
  - Can I create new maps in the 'resources' tab and make them available in the map-viewer?
- Is it possible to publish a QGIS project file onto the QGIS-server container and view it in the map-viewer?
  - In that case, how?
- What is the relation between the QGIS-server and the qwc-ogc-service container?

I refer these questions to @pka and @HusseinKabbout, hopefully you are in a position to answer.
If there are any unclarities, please do not hesitate to comment.

Best regards

**Comment by manisandro** [comment]
The updated [Readme](https://github.com/qwc-services/qwc-docker/blob/master/README.md) should answer these questions.
