### ISSUE TITLE
postgis persistent

### ISSUE THREAD

**Issue by joetha** [qwc-services/qwc-docker#34]
Hi,

I try to keep my database persistent by adding the following to the docker-compose.yml file:

  qwc-postgis:
    image: sourcepole/qwc-demo-db
    # build:
    #   context: ./postgis
    #   args:
    #     - ALEMBIC_VERSION=c77774920e5b
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
    ports:
     - "127.0.0.1:5439:5432"
    **_volumes:
     - ./volumes/postgisdb:/var/lib/postgresql/docker_**

The postgresql database is running and can be queried.

When calling the qwc_admin_gui in the browser
http://localhost:8088/auth/login?url=http://localhost:8088/qwc_admin/

the following error occurs:

**Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

Docker Logs say:

qwc-auth-service_1             | [2021-03-10 15:55:34,522] ERROR in app: Exception on /login [GET]
qwc-auth-service_1             | Traceback (most recent call last):
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
qwc-auth-service_1             |     response = self.full_dispatch_request()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
qwc-auth-service_1             |     rv = self.handle_user_exception(e)
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
qwc-auth-service_1             |     reraise(exc_type, exc_value, tb)
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
qwc-auth-service_1             |     raise value
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
qwc-auth-service_1             |     rv = self.dispatch_request()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
qwc-auth-service_1             |     return self.view_functions[rule.endpoint](**req.view_args)
qwc-auth-service_1             |   File "./server.py", line 79, in login
qwc-auth-service_1             |     return db_auth_handler().login()
qwc-auth-service_1             |   File "./server.py", line 68, in db_auth_handler
qwc-auth-service_1             |     'handler', tenant, DBAuth(tenant, mail, app))
qwc-auth-service_1             |   File "./db_auth.py", line 80, in __init__
qwc-auth-service_1             |     self.config_models = ConfigModels(db_engine, db_url)
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/qwc_services_core/config_models.py", line 27, in __init__
qwc-auth-service_1             |     self.init_models()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/qwc_services_core/config_models.py", line 74, in init_models
qwc-auth-service_1             |     Base.prepare()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/sqlalchemy/ext/automap.py", line 820, in prepare
qwc-auth-service_1             |     map_config.map()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 765, in map
qwc-auth-service_1             |     return super(_DeferredMapperConfig, self).map()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 696, in map
qwc-auth-service_1             |     self.cls, self.local_table, **self.mapper_args
qwc-auth-service_1             |   File "<string>", line 2, in mapper
qwc-auth-service_1             |   File "<string>", line 2, in __init__
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
qwc-auth-service_1             |     return fn(*args, **kwargs)
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 716, in __init__
qwc-auth-service_1             |     self._configure_pks()
qwc-auth-service_1             |   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1397, in _configure_pks
qwc-auth-service_1             |     % (self, self.persist_selectable.description)
qwc-auth-service_1             | sqlalchemy.exc.ArgumentError: Mapper mapped class User->users could not assemble any primary key columns for mapped table 'users'
qwc-auth-service_1             | [pid: 6|app: 0|req: 4/4] 192.168.144.15 () {56 vars in 1119 bytes} [Wed Mar 10 15:55:34 2021] GET /auth/login?url=http://localhost:8088/qwc_admin/ => generated 290 bytes in 38 msecs (HTTP/1.0 500) 2 headers in 84 bytes (1 switches on core 2)
qwc-api-gateway_1              | 192.168.144.1 - - [10/Mar/2021:15:55:34 +0000] "GET /auth/login?url=http://localhost:8088/qwc_admin/ HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36" "-"
qwc-map-viewer_1               | [pid: 6|app: 0|req: 4/4] 192.168.144.15 () {54 vars in 1005 bytes} [Wed Mar 10 15:55:34 2021] GET /favicon.ico => generated 232 bytes in 5 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 2)
qwc-api-gateway_1              | 192.168.144.1 - - [10/Mar/2021:15:55:34 +0000] "GET /favicon.ico HTTP/1.1" 404 232 "http://localhost:8088/auth/login?url=http://localhost:8088/qwc_admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36" "-"

What am I doing wrong?
Cheers Joerg

**Comment by manisandro** [comment]
The qwc-demo-db image is now tagged with a version, it will stay persistent until you change the version image again. Note that the demo db is just that, a demo db. For production use, you'll likely want to setup your own db container, starting with the qwc-config-db setup (https://github.com/qwc-services/qwc-config-db/).
