### ISSUE TITLE
Bad redirection after first login authentication

### ISSUE THREAD

**Issue by SIGISLV** [qwc-services/qwc-docker#35]
I have an 404 error after authentification on the [login url](http://localhost:8088/auth/login) it doesn't forward me to the [qwc_admin url](http://172.24.5.16:8088/qwc_admin). I need to put manully in the url the qwc_admin url so I can set some preferences and add some users.

I have used the basic docker-compose-example.yaml and I commented some services.

**Comment by manisandro** [comment]
This should be since fixed.
