### ISSUE TITLE
infinite redirections when calling qwc-admin-gui container directly

### ISSUE THREAD

**Issue by lovasoa** [qwc-services/qwc-docker#38]
When running docker-compose from qwc-services with the default configuration, loading

`http://127.0.0.1:5031`

creates an infinite chain of redirections : 

`http://127.0.0.1:5031` -> `http://127.0.0.1:5031/auth/login?url=http://127.0.0.1:5031/` -> `http://127.0.0.1:5031/auth/login?url=http://127.0.0.1:5031/auth/login?url=http:%2F%2F127.0.0.1:5031%2F` -> ... -> `http://127.0.0.1:5031/auth/login?url=http://127.0.0.1:5031/auth/login?url=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2Fauth%2Flogin%3Furl=http:%2F%2F127.0.0.1:5031%2F`

**Comment by manisandro** [comment]
This is since fixed.
