### ISSUE TITLE
link to qwc-demo-db gets an error 404

### ISSUE THREAD

**Issue by kahermann** [qwc-services/qwc-docker#42]
Hi,

link to qwc-demo-db: "https://github.com/qwc-services/qwc-demo-db-db" gets an error 404

"https://github.com/qwc-services/qwc-demo-db" works

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qwc-services/qwc-docker/commit/567b380e006bfc69b2fa4019ca8bcdea3830b454
