### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by demtotal** [qwc-services/qwc-docker#43]
Hello,

Does anyone know what could be the cause of this problem (see image below)
![issue111](https://user-images.githubusercontent.com/93119565/154308720-d7931848-e00f-4dab-be5e-baa63748e693.PNG)

Thanks in advance

**Comment by manisandro** [comment]
have a look at the docker-compose logs

**Comment by demtotal** [comment]
I checked them and it all seems normal to me except the api-gateway: there's a "cannot modify /etc/nginx/conf.d/default.conf"
![issue222](https://user-images.githubusercontent.com/93119565/154309549-38b395e5-c0c9-4b11-9928-28a237e93a88.PNG)

**Comment by pka** [comment]
The "Internal Server Error" is coming from QGIS Server. If you don't get a meaningful error message from QGIS server you have to narrow down the problem by removing layers from your project.

**Comment by demtotal** [comment]
Qgis server container shows no errors in the logs and the project is really simple with one layer well configured. Could it be a problem of version between the different containers ? 
Another (random) question: do i need to have postgresql installed locally on my host machine or the postgis docker container is sufficient?  (because i can't execute these two commands psql "service=qwc_configdb" # Config DB
psql "service=qwc_geodb" # Demo data DB ) 
![issue333](https://user-images.githubusercontent.com/93119565/154497354-c1783f68-8968-4c2f-b8de-26dbce5c36df.PNG)
 
Thank you.

**Comment by demtotal** [comment]
I  haven't yet found a solution to this weird problem but when i tested on my personnal windows laptop it worked well, maybe it's a problem in the docker installation on centos...
Anyway thanks for your help i'm closing this issue.

**Comment by demtotal** [comment]
Greetings,
@pka am i the only one who is facing this issue when repulling the images or is there some kind of error on the image? and when i try to build from qgis-server/Dockerfile i get an error in the middle of the installation (qgis-providers, python3-qgis, qgis-server), what cani do to solve this ?
Sorry for disturbing you,
Thanks in advance
![issue444](https://user-images.githubusercontent.com/93119565/154963252-54c91356-89d1-4f03-bf46-e433b8b908a3.PNG)
n

**Comment by manisandro** [comment]
Can you post the full logs? Looks like a problem with the qgis package in the repos.

**Comment by demtotal** [comment]
So, right now i'm on the tag v2021.12.20, on the docker-compose.yml file i changed qwc-qgis-server to do the build using the file qgis-server/Dockerfile (because i'm having an Internal Server Error 500 when using the image 'sourcepole/qwc-qgis-server:3.16-plugins', here's the service definition:
`  qwc-qgis-server:
    #image: sourcepole/qwc-qgis-server:3.16-plugins
    build: 
      context: ./
      dockerfile: qgis-server/Dockerfile
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - ./volumes/qgs-resources:/data:ro
      - ./volumes/geodata:/geodata:ro
      - ./pg_service.conf:/etc/postgresql-common/pg_service.conf:ro`
On the qgis-server/Dockerfile i added the prefix 'qgis-server/' near every ADD to point to the context files
So all executes well until the command 'RUN apt-get update && apt-get install -y qgis-server
' on line 33 here i get errors
Here's a sample of the error that i could see on the logs:
![issue_logs_1](https://user-images.githubusercontent.com/93119565/154971330-337119b3-7429-42c9-9d57-a8a2479cbb95.PNG)
![issue_logs_2](https://user-images.githubusercontent.com/93119565/154971341-fc8cb6e6-c45b-4d5b-84fa-e7c69ac2637d.PNG)

**Comment by pka** [comment]
Instead of building your own QGIS Server image, you could try an other version. See https://hub.docker.com/r/sourcepole/qwc-qgis-server/tags for the available images.

**Comment by demtotal** [comment]
Yes indeed the image sourcepole/qwc-qgis-server:3.16.13 works well for me!
Thanks for your assistance!
Have a good day.
