### ISSUE TITLE
Problem with the "Administration tool"

### ISSUE THREAD

**Issue by LP-Sonic** [qwc-services/qwc-docker#53]
Hello,

it would be very nice if someone could help me with problems with the administration tool.

As soon as I click on the "Generate service configuration"-button on the corresponding "QWC Admin" webfrontend, I still get errors.

As soon as the download of the project settings begins, the following error messages are displayed:

„CRITICAL: Could not get GetProjectSettings from http://localhost:8001/ows/qwc_demo:
HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /ows/qwc_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&CLEARCACHE=1 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING: Could not get capabilities for /ows/qwc_demo
INFO: Reading 'qwc_demo.qgs'“

I have the impression that the web server for the QGIS server is refusing the connection.
Do you have an idea what it could be?

I would be very grateful for your help.
I have attached the web output of the administration tool to the ticket.
![admintool_output](https://user-images.githubusercontent.com/118463544/206476519-0ca7a66c-43a6-48c1-a116-e912700de528.jpeg)

**Comment by manisandro** [comment]
Looks like a misconfiguration of `default_qgis_server_url` in `tenantConfig.json`. In the docker-compose environment it should read

    "default_qgis_server_url": "http://qwc-qgis-server/ows/",

and the config generator output should contain lines like

    INFO: Downloading GetProjectSettings from http://qwc-qgis-server/ows/XXXX

**Comment by LP-Sonic** [comment]
Hello Mr. Mani,

thank you for your help.
Thanks to your help, I now understand the function of the "qwc-api-gateway", which serves as a kind of central exchange. In addition, I was not aware that Docker containers can be addressed by aliases or names.

If I understand correctly, the Docker-Composition „qwc-services/qwc-docker“ should actually work right out of the box.


However, I still have a problem.
After I have reset the configuration to the original state, I only see the following after pressing the "Generate service configuration" button: "An error occurred" (see also attached screenshot).

![qwc_admin](https://user-images.githubusercontent.com/118463544/206653827-2837f99e-ccb8-4f17-a941-9937b6a5eb73.png)

Error messages are output in the logs for the docker containers, which you can see in the attached screenshot.

![screenshot_docker_logs](https://user-images.githubusercontent.com/118463544/206653850-d4bc2e92-5d70-4a38-acc4-c4ff277aa106.png)

I would be very grateful for any help in this matter.

**Comment by manisandro** [comment]
Yes, qwc-docker should work out-of-the-box. Could you try with a fresh clone of this repo and see if you still encounter any issues?

**Comment by manisandro** [comment]
Yes the core issues seems to be that https://gibs.earthdata.nasa.gov/ is unreachable, the rest is insufficient error handling within the config generator. `https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/1.0.0/WMTSCapabilities.xml` is reachable here, so perhaps an issue with your local network?

**Comment by LP-Sonic** [comment]
Hello Mr. Mani,

I also think it's the internet connection.
Our internet access is provided via a proxy server. The internet requests don't seem to be sent to the proxy server from the QGIS server.

However, I have modified the container file "yml" so that
the QGIS server uses the proxy server to access the internet (see screenshot).

![proxy_server_env](https://user-images.githubusercontent.com/118463544/207328411-b72aa832-53a8-4848-9f22-7d4bcaec5936.png)

From the following command you can see that the container for the QGIS server uses the proxy in the curl request.

![qgis_server_anfrage](https://user-images.githubusercontent.com/118463544/207328544-39d2104b-1399-4dde-a9cf-0fb064ca4e47.png)

It may of course be that the QGIS Server service still doesn't use the proxy server because the environment variable is ignored. 
Do you have any idea how I can ensure the use of the proxy server?

**Comment by manisandro** [comment]
There are some hints here https://issues.qgis.org/issues/16096, in particular lower-case vs upper-case http_proxy.

**Comment by LP-Sonic** [comment]
Hello Mr. Mani,

that was the solution!
I wouldn't have figured it out without your help, thank you ;)

Thank you also for the competent and quick help.
I am happy!

You are welcome to close the ticket.

**Comment by manisandro** [comment]
Glad you solved the issue
