### ISSUE TITLE
qwc-qgis-server gets killed shortly after start

### ISSUE THREAD

**Issue by meierrom** [qwc-services/qwc-docker#54]
Hi folks,

I'm facing issues with the new version of qwc-qgis-server (v3.22-plugins). It runs for a few seconds and then gets killed:

docker-compose up qwc-qgis-server

WARNING: The JWT_SECRET_KEY variable is not set. Defaulting to a blank string.
Creating network "qwc-docker_default" with the default driver
Creating qwc-docker_qwc-qgis-server_1 ... done
Attaching to qwc-docker_qwc-qgis-server_1
qwc-qgis-server_1              | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
qwc-qgis-server_1              | *** Running /etc/my_init.d/10_syslog-ng.init...
qwc-qgis-server_1              | syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
qwc-qgis-server_1              | [2023-01-29T09:54:15.491867] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
qwc-qgis-server_1              | /etc/my_init.d/10_syslog-ng.init: line 32:    13 Trace/breakpoint trap   (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS
qwc-qgis-server_1              | *** /etc/my_init.d/10_syslog-ng.init failed with status 1
qwc-qgis-server_1              | 
qwc-qgis-server_1              | *** Killing all processes...
qwc-docker_qwc-qgis-server_1 exited with code 1

Any ideas how to fix this?

Kind regards,
Roman

**Comment by tpo** [comment]
Looks like this problem: https://github.com/syslog-ng/syslog-ng/issues/1821

**Comment by meierrom** [comment]
Thanks for your fast reply!

Yeah, seems related. I'm running the container as root though.

**Comment by tpo** [comment]
And what's the platform you're running it on? Is it a vanilla virtual machine without any special restrictions or limitations? What's the distro and version of the platform the VM is running on? What's the docker version?

I'm asking all this to get a picture of your context. We've been running dockerised qwc mostly in Ubuntu and Debian VMs and haven't seen your problem yet.

**Comment by meierrom** [comment]
Hi!

I'm not using a vm and am not aware of special restrictions or limitations.

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

Docker version 18.09.1, build 4c52b90

Kind regards,
Roman

**Comment by meierrom** [comment]
Hi folks,

My docker version may have been too old or some docker packages were missing.

Anyway, I did a fresh installation of my docker installation. Now I use "Docker version 23.0.0, build e92dd87".

The problem no longer appears after this.

Kind regards,
Roman

**Comment by tpo** [comment]
Woah, thanks a lot @meierrom for reporting back a letting us know that you have been able to resolve the problem and how you did it. Congratulations! And sorry I wasn't able to help.

**Comment by meierrom** [comment]
@tpo: Believe me, you did help! Your were asking me important questions contributing to the solution. Thanks!
