### ISSUE TITLE
Connection to a PostGIS server

### ISSUE THREAD

**Issue by lperozzi** [qwc-services/qwc-docker#55]
I successfully been able to add a test project with local shapefiles. Now I would like to move further and setting up a connection to a PostGIS database that lies on a Postgres server. I tried to add the connection infos in `/pg_service.conf` file, but it seems to not detect the layer, after generating the configuration via the Admin GUI. I followed [these](https://github.com/qwc-services/qwc-docker#selected-configuration-topics) instructions, but I should make some mistake somewhere.

**Comment by tpo** [comment]
The connections infos in `/pg_service.conf` have to be reachable (that is correctly configured in docker-compose.yml and readable (that means `chgrp www-data docker-compose.yml`).

Once you've verified that is the case:

When you generate the configuration via the Admin GUI there's some output displayed. Could you paste that once you've verified the above?

**Comment by HusseinKabbout** [comment]
@lperozzi Are you still encountering this problem?
