### ISSUE TITLE
Access to data in default qgs project

### ISSUE THREAD

**Issue by GetBack2Basics** [qwc-services/qwc-docker#57]
QGIS doesn’t connect to postgres datasets that come with QWC2

DETAILS
QGS file in /GIS/qwc-docker/volumes/qgs-resources/ does not open in QGIS (qgis.org).

I can connect to DB from within qgis but the files used to make the home page are not accessible.
We need access to this db to be able to modify the demo with our own data.

Checked user and password in readme but it won't work

**Comment by GetBack2Basics** [comment]
Yes I have tried this. I can access the db directly from QGIS but not when
I use the qgs file in  volumes/qgs-resources/scan/

Please see
https://docs.google.com/document/d/1zrGpySDCP6jMvKuDKVEXQDwENJs8SOmAGaNZfHkPdZc/edit?usp=sharing

**Comment by lperozzi** [comment]
@GetBack2Basics it works for me if you define the `qwc_geodb` service (https://qwc-services.github.io/setup/quick-start/#add-a-qgis-project) in your local `.pg_service.conf`

**Comment by GetBack2Basics** [comment]
I followed these steps but when I open QGIS and try the example qgs file I
can not access the db with qwc_service as user and password.

Is there a video or screenshots of the process?

**Comment by lperozzi** [comment]
Is your local `.pg_service.conf` visible by environment variables? What OS you use?

**Comment by GetBack2Basics** [comment]
I initially followed the instructions in
https://github.com/qwc-services/qwc-docker which is somewhat different from
the link you shared.

I have now installed using https://qwc-services.github.io/setup/quick-start/

I can not find the qgz file it refers to

   - Open project demo-projects/natural-earth-countries.qgz with QGIS and
   save as
   volumes/config-in/default/qgis_projects/natural-earth-countries.qgs

There is a qgs file in qwc-services/qwc-docker/volumes/qgs-resources/scan/
- when I open this the country names dataset loads but not the country
polygon. Once this is fixed and the file saved as per the instructions, the
qgs project gets added to the admin console and is visible in the viewer.

So in this current version we
-. No longer put files
in /qwc-services/qwc-docker/volumes/qgs-resources/scan/

Where do we put shp/gpkg files?

Regards,

**Comment by manisandro** [comment]
> Where do we put shp/gpkg files?

Any files referenced by the qgs project need to be stored relatively to the project in such way that the path resolves within the docker volume. In short, it is easiest to store the files next to the project or in a subfolder relative to the project.
