### ISSUE TITLE
No such file or directory: '/srv/qwc_service/config_generator/../schemas/schema-versions.json'

### ISSUE THREAD

**Issue by stf-alexander** [qwc-services/qwc-docker#58]
Hello everyone,

after a fresh install of this repository, I get the following error while running the `generate service configuration` button in `/qwc_admin`

![Bildschirmfoto 2023-03-09 um 11 05 47 AM](https://user-images.githubusercontent.com/108333579/223989510-2a7b62fe-00b8-4d2e-8334-91557cb5fcec.png)

Seems like a typo in the file name:

![Bildschirmfoto 2023-03-09 um 11 08 45 AM](https://user-images.githubusercontent.com/108333579/223989684-83ec86c0-5cf1-4491-a716-ce0599ae679d.png)

I can see the files schema-versions-2023-lts.json and schema-versions-master.json but the file schema-versions.json is missing.

**Comment by benoitblanc** [comment]
Related to https://github.com/qwc-services/qwc-config-generator/issues/48

**Comment by pka** [comment]
@mwa Why does the config generator read `chema-versions.json`?

**Comment by mwa** [comment]
Fixed in `qwc-config-generator:v2023.2-lts` and `qwc-config-generator:v2023.03.09`
