### ISSUE TITLE
manifest for sourcepole/qwc-data-service:2023.1-lts not found

### ISSUE THREAD

**Issue by lperozzi** [qwc-services/qwc-docker#60]
Hi,
after start all containers, i have this error message:

ERROR: manifest for sourcepole/qwc-data-service:2023.1-lts not found: manifest unknown: manifest unknown

**Comment by lperozzi** [comment]
I think I have found the bug. In the docker-compose-example.yml file, it should be:


`
image: sourcepole/qwc-data-service:v2023.1-lts
`

instead of:

`image: sourcepole/qwc-data-service:2023.1-lts`

Also, the tag 2023.0-lts exists for sourcepole/qwc-map-viewer-demo, but not for v2023.1-lts.

**Comment by manisandro** [comment]
Thanks, fixed - and qwc-map-viewer-v2023.1-lts is now also tagged.
