### ISSUE TITLE
Customizing qwc viewer inside qwc-docker

### ISSUE THREAD

**Issue by lperozzi** [qwc-services/qwc-docker#62]
I followed [these](https://github.com/qwc-services/qwc-docker#customize-qwc2-viewer) consigns to customize the viewer. Then I copied the prod folder from inside qwc-docker/qwc2. Now my tree is something like this:

| Path                         | Description
|------------------------------|-------------------------------------------------------------------|
|`├─ ...`                  |                                                                   |
|`├─ qgs-resources/`                  |                                                                   |
|`├─ qwc2/`                      |                                                                   |
|`│  ├─ assets/`               |                         |
|`│  ├─ dist/`          |                           |
|`│  └─ prod/`              | copied with command `cp -a SRCDIR/prod/ $DSTDIR/volumes/qwc2/` |
|`│  └─ .gitignore`    |  |
|`├─ solr/`                   |                                              |

However, it doesn;t show up and at the console I have this error:

`Failed to load resource: the server responded with a status of 404 (NOT FOUND) http://localhost:8088/dist/QWC2App.js`

I think there is a problem in my tree. Should the `prod` folder be at the same level of `dist` and `assets`?

**Comment by HusseinKabbout** [comment]
Could you try to copy with `cp -a SRCDIR/prod/* $DSTDIR/volumes/qwc2/`?

**Comment by lperozzi** [comment]
Isn't `cp -a SRCDIR/prod/* $DSTDIR/volumes/qwc2/`?

**Comment by HusseinKabbout** [comment]
The JS files have to be placed under `volumes/qwc2/dist/`. See https://qwc-services.github.io/setup/services/qwc-map-viewer/

**Comment by HusseinKabbout** [comment]
Ah yes my bad, I didn't read correctly. The command should be `cp -a $SRCDIR/prod/* $DSTDIR/volumes/qwc2/`.

**Comment by lperozzi** [comment]
Ok cool, in this way it works (partially), thanks. 
The colorscheme that I defined isn't applied (it still applying the default one), but I maybe made some errors

**Comment by lperozzi** [comment]
I doubled check, and I thick there is a problem. After copying the `prod` folder inside `qwc2`, instead of taking the defined colorschema (defined in `colorschemes.css`, and set up in `config.json`, the colorscheme is always the default one.

**Comment by manisandro** [comment]
Is your `colorschemes.css` included in your `index.html`?

**Comment by lperozzi** [comment]
Ah true. By adding `colorschemes.css` in index.html it works
