### ISSUE TITLE
Editable layers from external Postgres database

### ISSUE THREAD

**Issue by lperozzi** [qwc-services/qwc-docker#63]
I successfully added some editable layers that lie on the container PostGIS database (e.g., by setting the `service` to `qwc_geodb`). I can edit layer from the map viewer and all work just fine.

Now, I would like to make the same with a layer that lie on an external PostGIS database (e.g. `polygon_test`). I'm able to view the layer and activate the editing on this layer, but when I start to edit, I have this error:

![image](https://user-images.githubusercontent.com/6198369/234784700-58256c5e-5040-41b8-becb-3a78347ee3e6.png)

However, the service `PatInfra` is well-defined in `pg_service.conf` (I'm able to see layers coming from this service). I'm not sure where I'm wrong. Has someone any hints?

**Comment by manisandro** [comment]
Check if `pg_service-write.conf` is used in `docker-compose.yml` and if yes, have you defined the service there?

**Comment by lperozzi** [comment]
It was exactly that. Many thanks @manisandro
