### ISSUE TITLE
Deploying qwc-docker to server

### ISSUE THREAD

**Issue by lperozzi** [qwc-services/qwc-docker#64]
I'm trying to deploy a simple qwc-docker configuration to a production server and manage it with gitlab runner. I have a working localhost configuration, but I'm not sure how to set up it for a production use. Is there any documentation for that. I've searched but found nothing. Many thanks for your help

**Comment by tpo** [comment]
Setting up qwc-docker localy and in production is exactly the same.

In production you will maybe tweak a thing or another but that depends on what you need. F.ex.:

- HTTPS certificates via certbot
- exposing port 80 via an external ethernet interface
- export shares with data via CIFS or NFS etc.

but that depends on what you want and what you need and then you adapt it accordingly.

So you first need to figure out what you want for yourself in the first place.

If you don't need anything special then you set up qwc-docker exactly as on your localhost, put a http proxy in front of it to forward trafic to it and you're done.

For documentation I suggest https://qwc-services.github.io/.

And once you know what you want and run into problems then I suggest you post about those specific problems you encounter.

I hope that clears it up for you.

**Comment by lperozzi** [comment]
Thanks for your reply @tpo.

I'm really not an expert, so I'm learning by trial and error. The first error I had, when deploying to the server was:

```
/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: 
Are you trying to mount a directory onto a file (or vice-versa)? 
Check if the specified host path exists and is the expected type
```

to bypass this error I had to create a Dockerfile with this command:

```
FROM nginx:1.19

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.template /etc/nginx/conf.d
```

and then put 

``` 
qwc-api-gateway:
    build: ./nginx
```

instead of 

``` 
qwc-api-gateway:
    image: nginx:1.19
```

in `docker-compose.yml`

It seems that it doesn't copy the contents of my mapped volumes on the server side. But again I'm far to be an expert and maybe I'm doing something odd on my side
