### ISSUE TITLE
Questions about renaming QWC2 elements

### ISSUE THREAD

**Issue by jshirokov-bs** [qwc-services/qwc-docker#66]
Hello!

1) How i can renaming Themes? I need another name - Projects.
2) I have several buttons in the menu with no name. Can I add arbitrary notation to them?
3) How can I replace the links at the bottom of the screen that lead to the home page?

Thanks!

**Comment by manisandro** [comment]
Please start by reading the documentation at https://qwc-services.github.io and then come back if any questions remain.
