### ISSUE TITLE
qwc-fulltext-search in production 

### ISSUE THREAD

**Issue by lperozzi** [qwc-services/qwc-docker#67]
I have this problem:

1. Using a gitlab_ci workflow, the solr service start, but there is the following permission issue:
   `cp: cannot create regular file '/var/solr/data/solr.xml': Permission denied`
   The workaround is to `docker restart qwc-solr`, server side

2. After restarting qwc-solr, the search does not work through the search bar, but by copying the url (obtained from the localhost search request) and change _localhost:8088_ with the _server address name_ I'm getting the good queried object.

Where I'm wrong?

**Comment by tpo** [comment]
> Using a gitlab_ci workflow, the solr service start, but there is the following permission issue:
cp: cannot create regular file '/var/solr/data/solr.xml': Permission denied
The workaround is to docker restart qwc-solr, server side

Have a look at the permissions.

Also I suggest one problem -> one ticket

**Comment by manisandro** [comment]
Closing, feel free to reopen if still relevant.
