### ISSUE TITLE
Could not get GetProjectSettings: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Fudimir** [qwc-services/qwc-docker#68]
Hello!

I am trying to upload a project, but this error appears during configuration (in the image). What could this be related to?

Thanks!

![image](https://github.com/qwc-services/qwc-docker/assets/136562220/3f18d2e2-4ee7-462d-9cfa-a1e042d7b698)

**Comment by manisandro** [comment]
Could you check the docker log whether it contains a full stacktrace?

**Comment by Fudimir** [comment]
> Could you check the docker log whether it contains a full stacktrace?

Yes, I looked into the logs and saw an identical situation, and a few other lines about the QGIS project (fires_2023) that interests me. 

![image](https://github.com/qwc-services/qwc-docker/assets/136562220/43996992-f387-420a-b4c3-4dfc89c1451f)

![image](https://github.com/qwc-services/qwc-docker/assets/136562220/027a6847-376c-4a39-baa9-8cf0b49d027e)

**Comment by Fudimir** [comment]
It is worth noting that before that I changed the data in tenantConfig.json and config.json (in qwc-docker/volumes/config-in/default), but only for changing UI

**Comment by manisandro** [comment]
If you are comfortable with docker etc, could you open a shell inside the qwc-config-service container

    $ docker-compose exec qwc-config-service

and then

    $ vi /srv/qwc_service/config_generator/capabilities_reader.py

and add `print(traceback.format_exc())` here [1], then exit vi and

    $ kill $(pidof uwsgi)

Then re-invoke the config-generator, and you should get the full traceback printed in the docker log.

[1] https://github.com/qwc-services/qwc-config-generator/blob/2023-lts/config_generator/capabilities_reader.py#LL210

**Comment by manisandro** [comment]
Closing, feel free to reopen if still relevant and you can provide additional info.
