### ISSUE TITLE
API Route & Reachable

### ISSUE THREAD

**Issue by michaely1607** [qwc-services/qwc-docker#69]
Hi, 

I just install qwc-service using docker,

I want to ask about API Route & Reachable like in QWC2 (Standalone), How can I install in this docker..?

![image](https://github.com/qwc-services/qwc-docker/assets/109126773/bed60b40-a36a-4658-bd1a-b91509f4745e)

Thanks You,

**Comment by tpo** [comment]
Maybe someone else will be able to help you, but me I am unable to understand your question.

**Comment by manisandro** [comment]
I think the question is how to enable the Routing functionality in QWC2. @michaely1607 you need to enable the `Routing` plugin, and set up a valhalla server, setting the `routingServiceUrl` in `config.json` accordingly. The easiest way to set up a valhalla server is by using the [docker-valhalla](https://github.com/gis-ops/docker-valhalla) docker image. For testing, you can also use the demo routing server at `https://valhalla1.openstreetmap.de/`.
