### ISSUE TITLE
Feature Info CSV Tabular export

### ISSUE THREAD

**Issue by Vianxz** [qwc-services/qwc-docker#73]
Hello!

In this [post](https://github.com/qgis/qwc2/pull/103) I understand that this is for the standalone version, is there a way for me to change the export into tabular format? Below is the export format that I currently have:

> parcelle,,
,gid,529100
,id,14118000IB0072
,commune,14118
,prefixe,0
,section,IB
,numero,72
,contenance,36281
,created,2001-09-28
,updated,2015-03-26
,geometry,"MULTIPOLYGON ... "
,,
commune,,
,gid,245
,id,14118
,nom,CAEN
,created,2001-11-22
,updated,2018-04-19
,geometry,"MULTIPOLYGON ... "

Thank You

**Comment by manisandro** [comment]
What do you mean by tabular format? Possibly you just want to open the CSV in a spreadsheet application?

**Comment by Vianxz** [comment]
I apologize, I meant how can i adjust my CSV export which is currently like this:

> parcelle,,
,gid,529100
,id,14118000IB0072
,commune,14118
,prefixe,0
,section,IB
,numero,72
,contenance,36281
,created,2001-09-28
,updated,2015-03-26
,geometry,"MULTIPOLYGON ... "
,,
commune,,
,gid,245
,id,14118
,nom,CAEN
,created,2001-11-22
,updated,2018-04-19
,geometry,"MULTIPOLYGON ... "

into tabular format from the feature info export to this:

> gid;id;nom;created;updated;geometry
245;14118;CAEN;2001-11-22;2018-04-19;MULTIPOLYGON ...
302;14327;HEROUVILLE SAINT CLAIR;2002-11-28;2018-04-23;MULTIPOLYGON ...
335;14437;MONDEVILLE;2002-12-05;2016-11-17;MULTIPOLYGON ...

**Comment by manisandro** [comment]
I believe CSV+ZIP does something similar do what you are requesting, otherwise you'll need to implement your own exporter, see https://github.com/qgis/qwc2-demo-app/blob/master/js/IdentifyExtensions.js

**Comment by Vianxz** [comment]
Yes, I am using the CSV and CSV+ZIP export you mentioned

When using CSV export I am getting this output:

> Countries: Spain
> "	""featurecla""	""Admin-0 country"""
> "	""sovereignt""	""Spain"""
> "	""sov_a3""	""ESP"""
> "	""adm0_dif""	""0"""
> "	""level""	""2"""

also when using CSV+ZIP, I would get mixed format, i have shorten it for example:

> Admin-0 country;Ethiopia;ETH;0;2;Sovereign country;Ethiopia;ETH;0;Ethiopia;ETH;0;Ethiopia;ETH;0;Ethiopia;Ethiopia;ETH;Ethiopia;-;Eth.;ET;

>     <table class=""attribute-list">	
>         <tbody>	
>         	
>                 <tr>	
>                     <td class="identify-attr-title wrap">	
>                         <i>featurecla</i>	
>                     </td>	
>                     <td class="identify-attr-value wrap">	
>                         Admin-0 country	
>                     </td>	
>                 </tr>	
>                 <tr>	
>                     <td class="identify-attr-title wrap">	
>                         <i>sovereignt</i>	
>                     </td>	
>                     <td class="identify-attr-value wrap">	
>                         Ethiopia	
>                     </td>

**Comment by Vianxz** [comment]
It took some time but got it to work. Thank you

**Comment by manisandro** [comment]
Hmm not sure I understand, but yes please do submit a PR
