### ISSUE TITLE
qwc-docker runs both nginx and apache2 web servers

### ISSUE THREAD

**Issue by loyeyoung** [qwc-services/qwc-docker#76]
**qwc-docker runs _both_ apache2 and nginx.** 

It seems unnecessary to have both apache2 and nginx running in the same docker. Because I am new to this project, I am uncertain which services run which, but it seems that all of them could be run on either one or the other. In the absence of compelling reasons to the contrary, the docker should standardize on one or the other.

Having both web servers in the same docker has the following negative consequences:
1. increases aggregate memory and CPU usage,
2. increases filesystem requirements of the docker and its containers,
3. increases maintenance burden of managing upgrades and idiosyncrasies of each web server,
4. increases the security risk surface area, and
5. increases system complexity.

Is there a reason for running _both_ apache2 and nginx? If not, I recommend standardizing on one or the other. (My personal preference is nginx, but reasonable minds could differ.)

**Comment by manisandro** [comment]
The only container using apache is `qwc-qgis-server`, which does so because it needs `mod_fcgi`.

**Comment by loyeyoung** [comment]
`nginx` can also implement FastCGI. See, e.g., https://www.digitalocean.com/community/tutorials/understanding-and-implementing-fastcgi-proxying-in-nginx

Consequently, the `qwc-qgis-server` can be migrated to nginx. 

I will post an issue in [that project](https://github.com/qwc-services/qwc-qgis-server), along with suggested arguments.
