### ISSUE TITLE
Exposing WFS Layers

### ISSUE THREAD

**Issue by ak1dos** [qwc-services/qwc-docker#78]
I have configured several QGIS projects exposing the data as both WMS and WFS.
When I launch the project configuration for qwc2 everything is fine as far as WMS is concerned. But all layers published as WFS are not exposed even if they are defined in the qgs file.

I try enable editing on my layer and work.

When I contact /ows with service=WFS it replies: Service unknown or unsupported

**Comment by manisandro** [comment]
WFS is disabled by default in the config generator. You can enable it with `generate_wfs_services: true` in the toplevel config section of the `tenantConfig.json` [1].

[1] https://qwc-services.github.io/master/references/qwc-config-generator/#config_generate_wfs_services
