### ISSUE TITLE
Debian 12 QWC2 docker compose stuck

### ISSUE THREAD

**Issue by toltojn** [qwc-services/qwc-docker#82]
I've installed docker version 26.1.4 on a debian 12 server. And after that I did the quick install steps on https://qwc-services.github.io/master/QuickStart/

The compose hangs at:

qwc-solr-1                     | 2024-06-18 09:16:04.643 INFO  (searcherExecutor-15-thread-1-processing-x:gdi) [   x:gdi] o.a.s.c.SolrCore [gdi]  Registered new searcher autowarm time: 0 ms
qwc-solr-1                     | 2024-06-18 09:16:04.649 INFO  (searcherExecutor-17-thread-1-processing-x:gettingstarted) [   x:gettingstarted] o.a.s.c.QuerySenderListener QuerySenderListener done.
qwc-solr-1                     | 2024-06-18 09:16:04.649 INFO  (searcherExecutor-17-thread-1-processing-x:gettingstarted) [   x:gettingstarted] o.a.s.h.c.SpellCheckComponent Loading spell index for spellchecker: default
qwc-solr-1                     | 2024-06-18 09:16:04.651 INFO  (searcherExecutor-17-thread-1-processing-x:gettingstarted) [   x:gettingstarted] o.a.s.c.SolrCore [gettingstarted]  Registered new searcher autowarm time: 0 ms

Maybe someone can point me in the right direction to solve this issue? I'm a bit new in the docker and linux business.

**Comment by manisandro** [comment]
Does the application respond? The log output you posted does not indicate anything which indicates a hang or a timeout.

**Comment by toltojn** [comment]
> Does the application respond? The log output you posted does not indicate anything which indicates a hang or a timeout.

Ai. Forgot to check the website. It is working! 

I thought that de docker compose up returned to the prompt when finished. My bad.
