### ISSUE TITLE
Setting the loglevel of services

### ISSUE THREAD

**Issue by qwenger** [qwc-services/qwc-docker#84]
Hi,

Currently, the QWC services that are based on Flask use the default Python `logger` loglevel, that is `WARNING`. This makes debugging in Docker challenging when running each service separately is not an option (typically when it comes to debugging their interplay as containers).

It would be nice to be able to change their loglevel, e.g. from the `docker-compose.yml` or an env variable, be it globally or for each service specifically, without having to compile custom images.

**Comment by manisandro** [comment]
Hi, setting FLASK_DEBUG=1 as ENV should work

**Comment by qwenger** [comment]
That's exactly the kind of variable I was looking for, but for some reason I overlooked it. My bad. Many thanks, it works!
